#247 Introduce two types of smart apps
beda-software/fhir-emr pull request #249
Opened 2024-05-30 20:45 UTC by ialakey

Introduce two types of smart apps

2024-05-31 02:40 UTC, ir4y commented
- [ ] Please don't add update smart app clients, since they are using during the demo.
 - [ ] Add international tests that uses API calls for `useSmartApps` hook

2024-05-31 02:43 UTC, ir4y commented on src/containers/PatientDetails/PatientApps/hooks.ts
> +        let resourceType = 'smart-on-fhir';
You can use `matchCurrentUserRole` here

2024-06-18 12:00 UTC, ruscoder requested changes

2024-06-18 12:00 UTC, ruscoder commented on src/containers/PatientDetails/PatientApps/__tests__/useSmartApps.test.ts
> +        const remoteData = result.current.appsRemoteData.data;
better not to call the variables like remoteData if it is not remotedata container, here it's just appData. It was a remoteData before accessing .data

2024-06-18 13:06 UTC, merged